### ISSUE TITLE
Modularity of JSON -

### ISSUE THREAD

**Issue by manjahdani** [Trusted-AI-Labs/APTITUDE_Toolbox#7]
Some elements of the current interaction protocol is application dependent and does not comply with the JSON philosophy that is 

<Property,Value> 

For example : 

{
    "Proc":{    
        "Tracker":{
            "type": "BBoxes2DTracker"
        },
        "BBoxes2DTracker":{
            "model_type": "SORT",
            "pref_implem": "Abewley"
        },
        "SORT":{
            "max_age": 10, 
            "min_hits": 3,
            "iou_thresh": 0.3,
            "memory_fade": 1.0
        }
    },
    "Preproc":{},
    "Postproc":{}
}

It's correct that this configuration has 3 properties (Proc, Preproc,Postpoc) 

Yet, if in PROC you have a property "Tracker".. Which is actually a value 

Instead one should have 

{
    "Proc":{    
        "task": {tracker}, 
        "model":{
            "model_type": "SORT",
            "pref_implem": "Abewley"
            "param":{
                     "max_age": 10, 
                     "min_hits": 3,
                     "iou_thresh": 0.3,
                     "memory_fade": 1.0}
          }
}

Also note that one must avoid the use of capital letter for convention for "properties". Those issues block the use of powerful tools as  https://github.com/google/gson

**Comment by JonathanSamelson** [comment]
This issue is now fixed by PR #8 

The new format is the following: 

```
{
    "proc":{
        "task": "",
        "output_type": "",
        "model_type": "",
        "pref_implem": "",
        "params":{
            ...
        }
    },
    "preproc":{},
    "postproc":{}
}
```

A skeleton for each detector/tracker can also be consulted here: 
https://github.com/Trusted-AI-Labs/APTITUDE_Toolbox/tree/main/configs
